apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
  labels:
    app: taskmanager
spec:
  type: LoadBalancer
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
